version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
secrets: open_ai

apache_fallback_resource: "/index.php"

command:
  build:
    - "composer update"

  test:
    - "vendor/bin/phpunit tests/"
